# Generated by Django 5.1.4 on 2024-12-17 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saverapp', '0004_personalinfo_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='passwordentry',
            name='user',
        ),
        migrations.DeleteModel(
            name='Personalinfo',
        ),
        migrations.DeleteModel(
            name='PasswordEntry',
        ),
    ]
