# Generated by Django 5.1.4 on 2024-12-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saverapp', '0006_passwordentry_personalinfo_delete_personinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
