# Generated by Django 5.1.4 on 2024-12-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saverapp', '0008_alter_personalinfo_email_alter_personalinfo_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
